openapi: 3.1.0
info:
  title: PinkCapy API
  version: 1.0.0
  description: API documentation for PinkCapy Retail E-commerce System

servers:
  - url: https://pinkcapy.dev/v1
    description: Production server
  - url: http://localhost:8000/v1
    description: Local development

paths:
  # Catalog API : @catalog
  /products/{id}: { $ref: './domain/catalog/index.yaml#/paths/~1products~1{id}' }
  /products/{slug}: { $ref: './domain/catalog/index.yaml#/paths/~1products~1{slug}' }
  /products/{id}/related: { $ref: './domain/catalog/index.yaml#/paths/~1products~1{id}~1related' }
  /products: { $ref: './domain/catalog/index.yaml#/paths/~1products' }

  /admin/products/{id}: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}' }
  /admin/products/{id}/metas: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1metas' }
  /admin/products/{id}/metas/{meta_id}: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1metas~1{meta_id}' }
  /admin/products/{id}/categories: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1categories' }
  /admin/products/{id}/tags: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1tags' }
  /admin/products/{id}/status: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1status' }
  /admin/products: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products' }
  /admin/products/{id}/inventories: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1products~1{id}~1inventories' }

  /tags/{id}/products: { $ref: './domain/catalog/index.yaml#/paths/~1tags~1{id}~1products' }
  /admin/tags: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1tags' }
  /admin/tags/{id}: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1tags~1{id}' }
  /categories: { $ref: './domain/catalog/index.yaml#/paths/~1categories' }
  /categories/{slug}: { $ref: './domain/catalog/index.yaml#/paths/~1categories~1{slug}' }
  /categories/{slug}/products: { $ref: './domain/catalog/index.yaml#/paths/~1categories~1{slug}~1products' }
  /admin/categories/{id}: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1categories~1{id}' }
  /admin/categories: { $ref: './domain/catalog/index.yaml#/paths/~1admin~1categories' }

  # Sales Domain : @sales
  /me/carts: { $ref: './domain/sales/index.yaml#/paths/~1me~1carts' }
  /me/carts/items: { $ref: './domain/sales/index.yaml#/paths/~1me~1carts~1items' }
  /me/carts/items/{id}: { $ref: './domain/sales/index.yaml#/paths/~1me~1carts~1items~1{id}' }
  /me/carts/clear: { $ref: './domain/sales/index.yaml#/paths/~1me~1carts~1clear' }
  /me/carts/checkout: { $ref: './domain/sales/index.yaml#/paths/~1me~1carts~1checkout' }
  /me/orders: { $ref: './domain/sales/index.yaml#/paths/~1me~1orders' }
  /me/orders/{id}: { $ref: './domain/sales/index.yaml#/paths/~1me~1orders~1{id}' }
  /me/orders/{id}/status: { $ref: './domain/sales/index.yaml#/paths/~1me~1orders~1{id}~1status' }
  /me/orders/{id}/shipping: { $ref: './domain/sales/index.yaml#/paths/~1me~1orders~1{id}~1shipping' }
  /me/orders/{id}/cancel: { $ref: './domain/sales/index.yaml#/paths/~1me~1orders~1{id}~1cancel' }

  /admin/orders: { $ref: './domain/sales/index.yaml#/paths/~1admin~1orders' }
  /admin/orders/{id}: { $ref: './domain/sales/index.yaml#/paths/~1admin~1orders~1{id}' }
  /admin/orders/{id}/status: { $ref: './domain/sales/index.yaml#/paths/~1admin~1orders~1{id}~1status' }
  /admin/orders/{id}/cancel: { $ref: './domain/sales/index.yaml#/paths/~1admin~1orders~1{id}~1cancel' }

  /admin/transactions: { $ref: './domain/sales/index.yaml#/paths/~1admin~1transactions' }

  /me: { $ref: './domain/identity/index.yaml#/paths/~1me' }
  /users/auth/register: { $ref: './domain/identity/index.yaml#/paths/~1users~1auth~1register' }
  /users/auth/login: { $ref: './domain/identity/index.yaml#/paths/~1users~1auth~1login' }
  /users/auth/logout: { $ref: './domain/identity/index.yaml#/paths/~1users~1auth~1logout' }
  /users/auth/forgot-password: { $ref: './domain/identity/index.yaml#/paths/~1users~1auth~1forgot-password' }
  /users/auth/reset-password: { $ref: './domain/identity/index.yaml#/paths/~1users~1auth~1reset-password' }
  /me/password: { $ref: './domain/identity/index.yaml#/paths/~1me~1password' }

  /admin/users: { $ref: './domain/identity/index.yaml#/paths/~1admin~1users' }
  /admin/users/{id}: { $ref: './domain/identity/index.yaml#/paths/~1admin~1users~1{id}' }
  /admin/users/{id}/status: { $ref: './domain/identity/index.yaml#/paths/~1admin~1users~1{id}~1status' }
  /admin/users/{id}/roles: { $ref: './domain/identity/index.yaml#/paths/~1admin~1users~1{id}~1roles' }

  # Analytics Domain: @analytics
  /admin/dashboard/overview: { $ref: './domain/analytics/index.yaml#/paths/~1admin~1dashboard~1overview' }
  /admin/dashboard/revenue: { $ref: './domain/analytics/index.yaml#/paths/~1admin~1dashboard~1revenue' }
  /admin/dashboard/orders/stats: { $ref: './domain/analytics/index.yaml#/paths/~1admin~1dashboard~1orders~1stats' }
  /admin/dashboard/products/top: { $ref: './domain/analytics/index.yaml#/paths/~1admin~1dashboard~1products~1top' } 

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    InfiniteScroll: { $ref: './shared/schemas.yaml#/InfiniteScroll' }
    Pagination: { $ref: './shared/schemas.yaml#/Pagination' }
    ResponseBase: { $ref: './shared/schemas.yaml#/ResponseBase' }
    Meta: { $ref: './shared/schemas.yaml#/Meta' }
    AuditFields: { $ref: './shared/schemas.yaml#/AuditFields' }

  parameters:
    SortParam: { $ref: './shared/parameters.yaml#/SortParam' }
    AuthorizationHeader: { $ref: './shared/parameters.yaml#/AuthorizationHeader' }
    IdempotencyKeyHeader: { $ref: './shared/parameters.yaml#/IdempotencyKeyHeader' }
    PageParam: { $ref: './shared/parameters.yaml#/PageParam' }
    SizeParam: { $ref: './shared/parameters.yaml#/SizeParam' }
    OffsetParam: { $ref: './shared/parameters.yaml#/OffsetParam' }
    LimitParam: { $ref: './shared/parameters.yaml#/LimitParam' }

  responses:
    BadRequest: { $ref: './shared/error.yaml#/BadRequest' }
    Unauthorized: { $ref: './shared/error.yaml#/Unauthorized' }
    ValidationError: { $ref: './shared/error.yaml#/ValidationError' }
    Forbidden: { $ref: './shared/error.yaml#/Forbidden' }
    NotFound: { $ref: './shared/error.yaml#/NotFound' }
    Conflict: { $ref: './shared/error.yaml#/Conflict' }
    InternalServerError: { $ref: './shared/error.yaml#/InternalServerError' }
    NoContent: { $ref: './shared/error.yaml#/NoContent' }

    # Identity Domain
    # ResetPasswordTokenInvalid: { $ref: './domain/identity/index.yaml#/components/responses/ResetPasswordTokenInvalid' }
